# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myserver.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_server_win(object):
    def setupUi(self, server_win):
        server_win.setObjectName("server_win")
        server_win.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(server_win)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(server_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.server_status = QtWidgets.QLabel(self.frame_2)
        self.server_status.setObjectName("server_status")
        self.gridLayout.addWidget(self.server_status, 0, 0, 1, 1)
        self.server_text = QtWidgets.QLineEdit(self.frame_2)
        self.server_text.setReadOnly(True)
        self.server_text.setObjectName("server_text")
        self.gridLayout.addWidget(self.server_text, 0, 1, 1, 1)
        self.database_status = QtWidgets.QLabel(self.frame_2)
        self.database_status.setObjectName("database_status")
        self.gridLayout.addWidget(self.database_status, 1, 0, 1, 1)
        self.database_text = QtWidgets.QLineEdit(self.frame_2)
        self.database_text.setReadOnly(True)
        self.database_text.setObjectName("database_text")
        self.gridLayout.addWidget(self.database_text, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(server_win)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_btn = QtWidgets.QPushButton(self.frame)
        self.open_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.open_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_btn.setStyleSheet("border:5px,outset,rgb(71, 71, 71);\n"
"border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.open_btn.setObjectName("open_btn")
        self.horizontalLayout.addWidget(self.open_btn)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(server_win)
        self.open_btn.clicked.connect(server_win.open_server_work)
        QtCore.QMetaObject.connectSlotsByName(server_win)

    def retranslateUi(self, server_win):
        _translate = QtCore.QCoreApplication.translate
        server_win.setWindowTitle(_translate("server_win", "服务器"))
        self.server_status.setText(_translate("server_win", "服务器状态"))
        self.database_status.setText(_translate("server_win", "数据库状态"))
        self.open_btn.setText(_translate("server_win", "开启服务器"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    server_win = QtWidgets.QWidget()
    ui = Ui_server_win()
    ui.setupUi(server_win)
    server_win.show()
    sys.exit(app.exec_())
