# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'answer_inter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_answer_to_enter_win(object):
    def setupUi(self, answer_to_enter_win):
        answer_to_enter_win.setObjectName("answer_to_enter_win")
        answer_to_enter_win.resize(549, 422)
        answer_to_enter_win.setMaximumSize(QtCore.QSize(10000000, 16777215))
        answer_to_enter_win.setStyleSheet("#answer_to_enter_win{\n"
"background-color: rgb(255, 255, 255);}\n"
"\n"
"#shower{\n"
"background-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"#refresh_btn{\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:5px;\n"
"font: 10pt \"微软雅黑\";\n"
"}\n"
"\n"
"#return_btn{\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:5px;\n"
"font: 10pt \"微软雅黑\";\n"
"}\n"
"\n"
"#tips{\n"
"\n"
"font: 10pt \"微软雅黑\";\n"
"}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(answer_to_enter_win)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tips = QtWidgets.QLabel(answer_to_enter_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tips.sizePolicy().hasHeightForWidth())
        self.tips.setSizePolicy(sizePolicy)
        self.tips.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tips.setAlignment(QtCore.Qt.AlignCenter)
        self.tips.setObjectName("tips")
        self.verticalLayout.addWidget(self.tips)
        self.shower = QtWidgets.QScrollArea(answer_to_enter_win)
        self.shower.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width:1px;\n"
"border-style:solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:5px;")
        self.shower.setWidgetResizable(True)
        self.shower.setObjectName("shower")
        self.shower_content = my_widget()
        self.shower_content.setGeometry(QtCore.QRect(0, 0, 529, 320))
        self.shower_content.setObjectName("shower_content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.shower_content)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.shower.setWidget(self.shower_content)
        self.verticalLayout.addWidget(self.shower)
        self.frame = QtWidgets.QFrame(answer_to_enter_win)
        self.frame.setStyleSheet("border-width:2px;\n"
"border-style:solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:5px;\n"
"background-color: rgb(104, 148, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refresh_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.refresh_btn.sizePolicy().hasHeightForWidth())
        self.refresh_btn.setSizePolicy(sizePolicy)
        self.refresh_btn.setMinimumSize(QtCore.QSize(50, 30))
        self.refresh_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.refresh_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout_2.addWidget(self.refresh_btn)
        self.return_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.return_btn.sizePolicy().hasHeightForWidth())
        self.return_btn.setSizePolicy(sizePolicy)
        self.return_btn.setMinimumSize(QtCore.QSize(50, 30))
        self.return_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.return_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.return_btn.setObjectName("return_btn")
        self.horizontalLayout_2.addWidget(self.return_btn)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(answer_to_enter_win)
        self.refresh_btn.clicked.connect(answer_to_enter_win.refresh_the_win)
        self.return_btn.clicked.connect(answer_to_enter_win.return_to_menu)
        QtCore.QMetaObject.connectSlotsByName(answer_to_enter_win)

    def retranslateUi(self, answer_to_enter_win):
        _translate = QtCore.QCoreApplication.translate
        answer_to_enter_win.setWindowTitle(_translate("answer_to_enter_win", "处理进入请求"))
        self.tips.setText(_translate("answer_to_enter_win", "点击刷新查询来访数据"))
        self.refresh_btn.setText(_translate("answer_to_enter_win", "刷新"))
        self.return_btn.setText(_translate("answer_to_enter_win", "返回"))
from new_Qwidget import my_widget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    answer_to_enter_win = QtWidgets.QWidget()
    ui = Ui_answer_to_enter_win()
    ui.setupUi(answer_to_enter_win)
    answer_to_enter_win.show()
    sys.exit(app.exec_())
