# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'answer_enter_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_answer_enter_item(object):
    def setupUi(self, answer_enter_item):
        answer_enter_item.setObjectName("answer_enter_item")
        answer_enter_item.resize(352, 60)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(answer_enter_item.sizePolicy().hasHeightForWidth())
        answer_enter_item.setSizePolicy(sizePolicy)
        answer_enter_item.setMinimumSize(QtCore.QSize(0, 60))
        answer_enter_item.setMaximumSize(QtCore.QSize(16777215, 60))
        answer_enter_item.setStyleSheet("#answer_enter_item{\n"
"background-color: rgb(104, 148, 0);\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:5px;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(answer_enter_item)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.time_text = QtWidgets.QLabel(answer_enter_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_text.sizePolicy().hasHeightForWidth())
        self.time_text.setSizePolicy(sizePolicy)
        self.time_text.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.time_text.setObjectName("time_text")
        self.horizontalLayout.addWidget(self.time_text)
        self.pushButton = QtWidgets.QPushButton(answer_enter_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:5px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(answer_enter_item)
        self.pushButton.clicked.connect(answer_enter_item.open_img_win)
        QtCore.QMetaObject.connectSlotsByName(answer_enter_item)

    def retranslateUi(self, answer_enter_item):
        _translate = QtCore.QCoreApplication.translate
        answer_enter_item.setWindowTitle(_translate("answer_enter_item", "Form"))
        self.time_text.setText(_translate("answer_enter_item", "time"))
        self.pushButton.setText(_translate("answer_enter_item", "进入查看"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    answer_enter_item = QtWidgets.QWidget()
    ui = Ui_answer_enter_item()
    ui.setupUi(answer_enter_item)
    answer_enter_item.show()
    sys.exit(app.exec_())
