# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_door_pw.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_door_pw(object):
    def setupUi(self, change_door_pw):
        change_door_pw.setObjectName("change_door_pw")
        change_door_pw.resize(400, 300)
        change_door_pw.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(change_door_pw)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(change_door_pw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.door_pw_text = QtWidgets.QLineEdit(self.frame_2)
        self.door_pw_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.door_pw_text.setObjectName("door_pw_text")
        self.gridLayout.addWidget(self.door_pw_text, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.manager_pw_text = QtWidgets.QLineEdit(self.frame_2)
        self.manager_pw_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.manager_pw_text.setObjectName("manager_pw_text")
        self.gridLayout.addWidget(self.manager_pw_text, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(change_door_pw)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.refresh_btn = QtWidgets.QPushButton(self.frame)
        self.refresh_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.refresh_btn.setObjectName("refresh_btn")
        self.verticalLayout.addWidget(self.refresh_btn)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(change_door_pw)
        self.refresh_btn.clicked.connect(change_door_pw.update_pw)
        QtCore.QMetaObject.connectSlotsByName(change_door_pw)

    def retranslateUi(self, change_door_pw):
        _translate = QtCore.QCoreApplication.translate
        change_door_pw.setWindowTitle(_translate("change_door_pw", "Form"))
        self.label.setText(_translate("change_door_pw", "门禁密码"))
        self.label_2.setText(_translate("change_door_pw", "管理员密钥"))
        self.refresh_btn.setText(_translate("change_door_pw", "更新"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    change_door_pw = QtWidgets.QWidget()
    ui = Ui_change_door_pw()
    ui.setupUi(change_door_pw)
    change_door_pw.show()
    sys.exit(app.exec_())
