# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_face.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_check_face_win(object):
    def setupUi(self, check_face_win):
        check_face_win.setObjectName("check_face_win")
        check_face_win.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(check_face_win)
        self.verticalLayout.setObjectName("verticalLayout")
        self.my_table = QtWidgets.QTableWidget(check_face_win)
        self.my_table.setObjectName("my_table")
        self.my_table.setColumnCount(5)
        self.my_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.my_table)
        self.delete_btn = QtWidgets.QPushButton(check_face_win)
        self.delete_btn.setObjectName("delete_btn")
        self.verticalLayout.addWidget(self.delete_btn)

        self.retranslateUi(check_face_win)
        self.my_table.itemClicked['QTableWidgetItem*'].connect(check_face_win.choose_one)
        self.delete_btn.clicked.connect(check_face_win.delete_face)
        QtCore.QMetaObject.connectSlotsByName(check_face_win)

    def retranslateUi(self, check_face_win):
        _translate = QtCore.QCoreApplication.translate
        check_face_win.setWindowTitle(_translate("check_face_win", "Form"))
        item = self.my_table.horizontalHeaderItem(0)
        item.setText(_translate("check_face_win", "id"))
        item = self.my_table.horizontalHeaderItem(1)
        item.setText(_translate("check_face_win", "姓名"))
        item = self.my_table.horizontalHeaderItem(2)
        item.setText(_translate("check_face_win", "单元号"))
        item = self.my_table.horizontalHeaderItem(3)
        item.setText(_translate("check_face_win", "房号"))
        item = self.my_table.horizontalHeaderItem(4)
        item.setText(_translate("check_face_win", "人脸录入状态"))
        self.delete_btn.setText(_translate("check_face_win", "删除"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    check_face_win = QtWidgets.QWidget()
    ui = Ui_check_face_win()
    ui.setupUi(check_face_win)
    check_face_win.show()
    sys.exit(app.exec_())
