# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_main_win(object):
    def setupUi(self, login_main_win):
        login_main_win.setObjectName("login_main_win")
        login_main_win.resize(509, 362)
        login_main_win.setMinimumSize(QtCore.QSize(0, 0))
        login_main_win.setMaximumSize(QtCore.QSize(10000, 10000))
        login_main_win.setStyleSheet("#ac_pw_widget{\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid}\n"
"\n"
"#login_main_win{\n"
"background-color: rgb(255, 255, 255);}\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(login_main_win)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(login_main_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.main_widget = QtWidgets.QWidget(login_main_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.main_widget.sizePolicy().hasHeightForWidth())
        self.main_widget.setSizePolicy(sizePolicy)
        self.main_widget.setStyleSheet("#main_widget{\n"
"background-color: rgb(104, 148, 0);\n"
"border-radius:5px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid}")
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ac_pw_widget = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ac_pw_widget.sizePolicy().hasHeightForWidth())
        self.ac_pw_widget.setSizePolicy(sizePolicy)
        self.ac_pw_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ac_pw_widget.setObjectName("ac_pw_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.ac_pw_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.ac_pw_widget)
        self.label_3.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.actext = QtWidgets.QComboBox(self.ac_pw_widget)
        self.actext.setEditable(True)
        self.actext.setObjectName("actext")
        self.actext.addItem("")
        self.gridLayout.addWidget(self.actext, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.ac_pw_widget)
        self.label_4.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.pwtext = QtWidgets.QLineEdit(self.ac_pw_widget)
        self.pwtext.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwtext.setClearButtonEnabled(True)
        self.pwtext.setObjectName("pwtext")
        self.gridLayout.addWidget(self.pwtext, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.ac_pw_widget)
        self.frame_2 = QtWidgets.QFrame(self.main_widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.autologinbtn = QtWidgets.QCheckBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autologinbtn.sizePolicy().hasHeightForWidth())
        self.autologinbtn.setSizePolicy(sizePolicy)
        self.autologinbtn.setObjectName("autologinbtn")
        self.horizontalLayout.addWidget(self.autologinbtn)
        self.rempwbtn = QtWidgets.QCheckBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rempwbtn.sizePolicy().hasHeightForWidth())
        self.rempwbtn.setSizePolicy(sizePolicy)
        self.rempwbtn.setObjectName("rempwbtn")
        self.horizontalLayout.addWidget(self.rempwbtn)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.main_widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.registerbtn = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerbtn.sizePolicy().hasHeightForWidth())
        self.registerbtn.setSizePolicy(sizePolicy)
        self.registerbtn.setStyleSheet("border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"微软雅黑\";")
        self.registerbtn.setObjectName("registerbtn")
        self.horizontalLayout_2.addWidget(self.registerbtn)
        self.loadbtn = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadbtn.sizePolicy().hasHeightForWidth())
        self.loadbtn.setSizePolicy(sizePolicy)
        self.loadbtn.setMinimumSize(QtCore.QSize(0, 30))
        self.loadbtn.setStyleSheet("QPushButton{\n"
"background-color: rgb(202, 0, 0);\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"微软雅黑\";}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(195, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    rgb(0, 255, 170);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145);\n"
"}\n"
"\n"
"\n"
"")
        self.loadbtn.setObjectName("loadbtn")
        self.horizontalLayout_2.addWidget(self.loadbtn)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.main_widget)

        self.retranslateUi(login_main_win)
        self.registerbtn.clicked.connect(login_main_win.showregister)
        self.rempwbtn.clicked['bool'].connect(login_main_win.rempw)
        self.loadbtn.clicked.connect(login_main_win.login)
        self.autologinbtn.clicked['bool'].connect(login_main_win.autologin)
        QtCore.QMetaObject.connectSlotsByName(login_main_win)

    def retranslateUi(self, login_main_win):
        _translate = QtCore.QCoreApplication.translate
        login_main_win.setWindowTitle(_translate("login_main_win", "登录"))
        self.label_3.setText(_translate("login_main_win", "账 号"))
        self.actext.setPlaceholderText(_translate("login_main_win", "请输入账号"))
        self.actext.setItemText(0, _translate("login_main_win", "123456"))
        self.label_4.setText(_translate("login_main_win", "密 码"))
        self.pwtext.setText(_translate("login_main_win", "123456"))
        self.pwtext.setPlaceholderText(_translate("login_main_win", "请输入密码"))
        self.autologinbtn.setText(_translate("login_main_win", "自动登录"))
        self.rempwbtn.setText(_translate("login_main_win", "记住密码"))
        self.registerbtn.setText(_translate("login_main_win", "注  册"))
        self.loadbtn.setText(_translate("login_main_win", "登    录"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_main_win = QtWidgets.QWidget()
    ui = Ui_login_main_win()
    ui.setupUi(login_main_win)
    login_main_win.show()
    sys.exit(app.exec_())
