# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu_win(object):
    def setupUi(self, menu_win):
        menu_win.setObjectName("menu_win")
        menu_win.resize(625, 529)
        menu_win.setStyleSheet("#menu_win{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#inner_label{\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"font: 75 20pt \"微软雅黑\";\n"
"}\n"
"\n"
"#user_top_widget{\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"background-color: rgb(104, 148, 0);\n"
"}\n"
"\n"
"#manager_top_widget{\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"background-color: rgb(104, 148, 0);\n"
"}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(menu_win)
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_top_widget = QtWidgets.QWidget(menu_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.user_top_widget.sizePolicy().hasHeightForWidth())
        self.user_top_widget.setSizePolicy(sizePolicy)
        self.user_top_widget.setObjectName("user_top_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.user_top_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.face_intake_btn = QtWidgets.QPushButton(self.user_top_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.face_intake_btn.sizePolicy().hasHeightForWidth())
        self.face_intake_btn.setSizePolicy(sizePolicy)
        self.face_intake_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(202, 0, 0);\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"微软雅黑\";}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(195, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    rgb(0, 255, 170);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145);\n"
"}")
        self.face_intake_btn.setObjectName("face_intake_btn")
        self.horizontalLayout.addWidget(self.face_intake_btn)
        self.answer_to_enter_btn = QtWidgets.QPushButton(self.user_top_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer_to_enter_btn.sizePolicy().hasHeightForWidth())
        self.answer_to_enter_btn.setSizePolicy(sizePolicy)
        self.answer_to_enter_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(202, 0, 0);\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"微软雅黑\";}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(195, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    rgb(0, 255, 170);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145);\n"
"}")
        self.answer_to_enter_btn.setObjectName("answer_to_enter_btn")
        self.horizontalLayout.addWidget(self.answer_to_enter_btn)
        self.teenager_btn = QtWidgets.QPushButton(self.user_top_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teenager_btn.sizePolicy().hasHeightForWidth())
        self.teenager_btn.setSizePolicy(sizePolicy)
        self.teenager_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(202, 0, 0);\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"微软雅黑\";}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(195, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    rgb(0, 255, 170);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145);\n"
"}")
        self.teenager_btn.setObjectName("teenager_btn")
        self.horizontalLayout.addWidget(self.teenager_btn)
        self.verticalLayout.addWidget(self.user_top_widget)
        self.manager_top_widget = QtWidgets.QWidget(menu_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.manager_top_widget.sizePolicy().hasHeightForWidth())
        self.manager_top_widget.setSizePolicy(sizePolicy)
        self.manager_top_widget.setObjectName("manager_top_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.manager_top_widget)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_user_imfor_btn = QtWidgets.QPushButton(self.manager_top_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_user_imfor_btn.sizePolicy().hasHeightForWidth())
        self.check_user_imfor_btn.setSizePolicy(sizePolicy)
        self.check_user_imfor_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(202, 0, 0);\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"微软雅黑\";}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(195, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    rgb(0, 255, 170);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145);\n"
"}")
        self.check_user_imfor_btn.setObjectName("check_user_imfor_btn")
        self.horizontalLayout_2.addWidget(self.check_user_imfor_btn)
        self.check_acpw = QtWidgets.QPushButton(self.manager_top_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_acpw.sizePolicy().hasHeightForWidth())
        self.check_acpw.setSizePolicy(sizePolicy)
        self.check_acpw.setStyleSheet("QPushButton{\n"
"background-color: rgb(202, 0, 0);\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"微软雅黑\";}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(195, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    rgb(0, 255, 170);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145);\n"
"}")
        self.check_acpw.setObjectName("check_acpw")
        self.horizontalLayout_2.addWidget(self.check_acpw)
        self.pushButton = QtWidgets.QPushButton(self.manager_top_widget)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(202, 0, 0);\n"
"border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"微软雅黑\";}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(195, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    rgb(0, 255, 170);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgb(145, 145, 145);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.manager_top_widget)
        self.shower = my_widget(menu_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.shower.sizePolicy().hasHeightForWidth())
        self.shower.setSizePolicy(sizePolicy)
        self.shower.setStyleSheet("")
        self.shower.setObjectName("shower")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.shower)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inner_label = QtWidgets.QLabel(self.shower)
        self.inner_label.setStyleSheet("")
        self.inner_label.setAlignment(QtCore.Qt.AlignCenter)
        self.inner_label.setObjectName("inner_label")
        self.verticalLayout_2.addWidget(self.inner_label)
        self.verticalLayout.addWidget(self.shower)

        self.retranslateUi(menu_win)
        self.face_intake_btn.clicked.connect(menu_win.open_face_intake_win)
        self.answer_to_enter_btn.clicked.connect(menu_win.open_answer_win)
        self.check_user_imfor_btn.clicked.connect(menu_win.open_user_imfor)
        self.teenager_btn.clicked.connect(menu_win.open_teenager_record)
        self.check_acpw.clicked.connect(menu_win.open_change_door_pw)
        self.pushButton.clicked.connect(menu_win.open_check_face)
        QtCore.QMetaObject.connectSlotsByName(menu_win)

    def retranslateUi(self, menu_win):
        _translate = QtCore.QCoreApplication.translate
        menu_win.setWindowTitle(_translate("menu_win", "主菜单"))
        self.face_intake_btn.setText(_translate("menu_win", "人脸录入"))
        self.answer_to_enter_btn.setText(_translate("menu_win", "处理进入请求"))
        self.teenager_btn.setText(_translate("menu_win", "查看未成年进出记录"))
        self.check_user_imfor_btn.setText(_translate("menu_win", "用户信息查看修改"))
        self.check_acpw.setText(_translate("menu_win", "修改门禁密码和管理员密钥"))
        self.pushButton.setText(_translate("menu_win", "管理住户人脸录入情况"))
        self.inner_label.setText(_translate("menu_win", "欢迎进入FPD人脸识别门禁管理系统"))
from new_Qwidget import my_widget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu_win = QtWidgets.QWidget()
    ui = Ui_menu_win()
    ui.setupUi(menu_win)
    menu_win.show()
    sys.exit(app.exec_())
