# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'takephoto.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_takephotomainwindow(object):
    def setupUi(self, takephotomainwindow):
        takephotomainwindow.setObjectName("takephotomainwindow")
        takephotomainwindow.resize(564, 457)
        takephotomainwindow.setStyleSheet("#widget_2{\n"
"border-width:2px;\n"
"font: 75 12pt \"微软雅黑\";\n"
"border-style:solid;\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"#takephotomainwindow{background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#widget{\n"
"border-width:2px;\n"
"font: 75 12pt \"微软雅黑\";\n"
"border-style:solid;\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(104, 148, 0);}\n"
"\n"
"\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(takephotomainwindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(takephotomainwindow)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.camera_window = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_window.sizePolicy().hasHeightForWidth())
        self.camera_window.setSizePolicy(sizePolicy)
        self.camera_window.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"text_align:center;\n"
"border:1px,solid,rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"微软雅黑\";")
        self.camera_window.setScaledContents(True)
        self.camera_window.setAlignment(QtCore.Qt.AlignCenter)
        self.camera_window.setObjectName("camera_window")
        self.verticalLayout.addWidget(self.camera_window)
        self.process_bar = QtWidgets.QProgressBar(self.widget_2)
        self.process_bar.setProperty("value", 0)
        self.process_bar.setInvertedAppearance(False)
        self.process_bar.setObjectName("process_bar")
        self.verticalLayout.addWidget(self.process_bar)
        self.sign_text = QtWidgets.QLabel(self.widget_2)
        self.sign_text.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.sign_text.setAlignment(QtCore.Qt.AlignCenter)
        self.sign_text.setObjectName("sign_text")
        self.verticalLayout.addWidget(self.sign_text)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(takephotomainwindow)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_camera_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_camera_btn.sizePolicy().hasHeightForWidth())
        self.open_camera_btn.setSizePolicy(sizePolicy)
        self.open_camera_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.open_camera_btn.setMaximumSize(QtCore.QSize(200, 50))
        self.open_camera_btn.setStyleSheet("border-width:2px;\n"
"font: 75 12pt \"微软雅黑\";\n"
"border-style:solid;\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.open_camera_btn.setObjectName("open_camera_btn")
        self.horizontalLayout.addWidget(self.open_camera_btn)
        self.close_camera_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_camera_btn.sizePolicy().hasHeightForWidth())
        self.close_camera_btn.setSizePolicy(sizePolicy)
        self.close_camera_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.close_camera_btn.setMaximumSize(QtCore.QSize(200, 50))
        self.close_camera_btn.setStyleSheet("border-width:2px;\n"
"font: 75 12pt \"微软雅黑\";\n"
"border-style:solid;\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.close_camera_btn.setObjectName("close_camera_btn")
        self.horizontalLayout.addWidget(self.close_camera_btn)
        self.take_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.take_btn.sizePolicy().hasHeightForWidth())
        self.take_btn.setSizePolicy(sizePolicy)
        self.take_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.take_btn.setMaximumSize(QtCore.QSize(200, 50))
        self.take_btn.setStyleSheet("border-width:2px;\n"
"font: 75 12pt \"微软雅黑\";\n"
"border-style:solid;\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.take_btn.setObjectName("take_btn")
        self.horizontalLayout.addWidget(self.take_btn)
        self.return_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.return_btn.sizePolicy().hasHeightForWidth())
        self.return_btn.setSizePolicy(sizePolicy)
        self.return_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.return_btn.setMaximumSize(QtCore.QSize(200, 50))
        self.return_btn.setStyleSheet("border-width:2px;\n"
"font: 75 12pt \"微软雅黑\";\n"
"border-style:solid;\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.return_btn.setObjectName("return_btn")
        self.horizontalLayout.addWidget(self.return_btn)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(takephotomainwindow)
        self.open_camera_btn.clicked.connect(takephotomainwindow.open_camera)
        self.close_camera_btn.clicked.connect(takephotomainwindow.close_camera)
        self.take_btn.clicked.connect(takephotomainwindow.open_takephoto_threading)
        self.return_btn.clicked.connect(takephotomainwindow.return_to_menu)
        QtCore.QMetaObject.connectSlotsByName(takephotomainwindow)

    def retranslateUi(self, takephotomainwindow):
        _translate = QtCore.QCoreApplication.translate
        takephotomainwindow.setWindowTitle(_translate("takephotomainwindow", "Form"))
        self.camera_window.setText(_translate("takephotomainwindow", "请打开摄像头"))
        self.sign_text.setText(_translate("takephotomainwindow", "采集人脸未开始"))
        self.open_camera_btn.setText(_translate("takephotomainwindow", "打开摄像头"))
        self.close_camera_btn.setText(_translate("takephotomainwindow", "关闭摄像头"))
        self.take_btn.setText(_translate("takephotomainwindow", "拍张靓照"))
        self.return_btn.setText(_translate("takephotomainwindow", "返回"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    takephotomainwindow = QtWidgets.QWidget()
    ui = Ui_takephotomainwindow()
    ui.setupUi(takephotomainwindow)
    takephotomainwindow.show()
    sys.exit(app.exec_())
