# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teenager_record_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_teenager_record_win(object):
    def setupUi(self, teenager_record_win):
        teenager_record_win.setObjectName("teenager_record_win")
        teenager_record_win.resize(466, 356)
        self.verticalLayout = QtWidgets.QVBoxLayout(teenager_record_win)
        self.verticalLayout.setObjectName("verticalLayout")
        self.my_table = QtWidgets.QTableWidget(teenager_record_win)
        self.my_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.my_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.my_table.setObjectName("my_table")
        self.my_table.setColumnCount(3)
        self.my_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(2, item)
        self.my_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.my_table)
        self.refresh_btn = QtWidgets.QPushButton(teenager_record_win)
        self.refresh_btn.setObjectName("refresh_btn")
        self.verticalLayout.addWidget(self.refresh_btn)

        self.retranslateUi(teenager_record_win)
        self.refresh_btn.clicked.connect(teenager_record_win.make_data_threading)
        QtCore.QMetaObject.connectSlotsByName(teenager_record_win)

    def retranslateUi(self, teenager_record_win):
        _translate = QtCore.QCoreApplication.translate
        teenager_record_win.setWindowTitle(_translate("teenager_record_win", "Form"))
        item = self.my_table.horizontalHeaderItem(0)
        item.setText(_translate("teenager_record_win", "姓名"))
        item = self.my_table.horizontalHeaderItem(1)
        item.setText(_translate("teenager_record_win", "年龄"))
        item = self.my_table.horizontalHeaderItem(2)
        item.setText(_translate("teenager_record_win", "进出时间"))
        self.refresh_btn.setText(_translate("teenager_record_win", "刷新"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    teenager_record_win = QtWidgets.QWidget()
    ui = Ui_teenager_record_win()
    ui.setupUi(teenager_record_win)
    teenager_record_win.show()
    sys.exit(app.exec_())
