# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_imformation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_table_user_imfor(object):
    def setupUi(self, table_user_imfor):
        table_user_imfor.setObjectName("table_user_imfor")
        table_user_imfor.resize(376, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(table_user_imfor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.my_table = QtWidgets.QTableWidget(table_user_imfor)
        self.my_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.my_table.setObjectName("my_table")
        self.my_table.setColumnCount(9)
        self.my_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_table.setHorizontalHeaderItem(8, item)
        self.my_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.my_table)
        self.frame = QtWidgets.QFrame(table_user_imfor)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(self.frame)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.delete_btn = QtWidgets.QPushButton(self.frame)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)
        self.change_btn = QtWidgets.QPushButton(self.frame)
        self.change_btn.setObjectName("change_btn")
        self.horizontalLayout.addWidget(self.change_btn)
        self.select_btn = QtWidgets.QPushButton(self.frame)
        self.select_btn.setObjectName("select_btn")
        self.horizontalLayout.addWidget(self.select_btn)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(table_user_imfor)
        self.my_table.itemClicked['QTableWidgetItem*'].connect(table_user_imfor.choose_one)
        self.change_btn.clicked.connect(table_user_imfor.my_update)
        self.add_btn.clicked.connect(table_user_imfor.my_add)
        self.delete_btn.clicked.connect(table_user_imfor.my_delete)
        self.select_btn.clicked.connect(table_user_imfor.my_select)
        QtCore.QMetaObject.connectSlotsByName(table_user_imfor)

    def retranslateUi(self, table_user_imfor):
        _translate = QtCore.QCoreApplication.translate
        table_user_imfor.setWindowTitle(_translate("table_user_imfor", "Form"))
        item = self.my_table.horizontalHeaderItem(0)
        item.setText(_translate("table_user_imfor", "账号"))
        item = self.my_table.horizontalHeaderItem(1)
        item.setText(_translate("table_user_imfor", "密码"))
        item = self.my_table.horizontalHeaderItem(2)
        item.setText(_translate("table_user_imfor", "姓名"))
        item = self.my_table.horizontalHeaderItem(3)
        item.setText(_translate("table_user_imfor", "年龄"))
        item = self.my_table.horizontalHeaderItem(4)
        item.setText(_translate("table_user_imfor", "性别"))
        item = self.my_table.horizontalHeaderItem(5)
        item.setText(_translate("table_user_imfor", "邮箱"))
        item = self.my_table.horizontalHeaderItem(6)
        item.setText(_translate("table_user_imfor", "权限"))
        item = self.my_table.horizontalHeaderItem(7)
        item.setText(_translate("table_user_imfor", "单元号"))
        item = self.my_table.horizontalHeaderItem(8)
        item.setText(_translate("table_user_imfor", "房号"))
        self.add_btn.setText(_translate("table_user_imfor", "增加"))
        self.delete_btn.setText(_translate("table_user_imfor", "删除"))
        self.change_btn.setText(_translate("table_user_imfor", "修改"))
        self.select_btn.setText(_translate("table_user_imfor", "查询"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    table_user_imfor = QtWidgets.QWidget()
    ui = Ui_table_user_imfor()
    ui.setupUi(table_user_imfor)
    table_user_imfor.show()
    sys.exit(app.exec_())
