# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ask_to_enter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ask_to_enter_win(object):
    def setupUi(self, ask_to_enter_win):
        ask_to_enter_win.setObjectName("ask_to_enter_win")
        ask_to_enter_win.resize(400, 300)
        ask_to_enter_win.setMinimumSize(QtCore.QSize(400, 300))
        ask_to_enter_win.setMaximumSize(QtCore.QSize(400, 300))
        ask_to_enter_win.setStyleSheet("#ask_to_enter_win{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ask_to_enter_win)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(ask_to_enter_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 11pt \"微软雅黑\";")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.led_signal = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.led_signal.sizePolicy().hasHeightForWidth())
        self.led_signal.setSizePolicy(sizePolicy)
        self.led_signal.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.led_signal.setAlignment(QtCore.Qt.AlignCenter)
        self.led_signal.setObjectName("led_signal")
        self.horizontalLayout_2.addWidget(self.led_signal)
        self.verticalLayout.addWidget(self.widget)
        self.imfor_frame = QtWidgets.QFrame(ask_to_enter_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.imfor_frame.sizePolicy().hasHeightForWidth())
        self.imfor_frame.setSizePolicy(sizePolicy)
        self.imfor_frame.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.imfor_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imfor_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imfor_frame.setObjectName("imfor_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.imfor_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.house_num_text = QtWidgets.QLabel(self.imfor_frame)
        self.house_num_text.setObjectName("house_num_text")
        self.gridLayout.addWidget(self.house_num_text, 0, 0, 1, 1)
        self.house_num_input = QtWidgets.QComboBox(self.imfor_frame)
        self.house_num_input.setObjectName("house_num_input")
        self.house_num_input.addItem("")
        self.house_num_input.addItem("")
        self.house_num_input.addItem("")
        self.house_num_input.addItem("")
        self.house_num_input.addItem("")
        self.house_num_input.addItem("")
        self.house_num_input.addItem("")
        self.house_num_input.addItem("")
        self.gridLayout.addWidget(self.house_num_input, 0, 1, 1, 1)
        self.room_num_text = QtWidgets.QLabel(self.imfor_frame)
        self.room_num_text.setObjectName("room_num_text")
        self.gridLayout.addWidget(self.room_num_text, 1, 0, 1, 1)
        self.room_num_input = QtWidgets.QLineEdit(self.imfor_frame)
        self.room_num_input.setObjectName("room_num_input")
        self.gridLayout.addWidget(self.room_num_input, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.imfor_frame)
        self.frame = QtWidgets.QFrame(ask_to_enter_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("border-width:2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-radius:5px;\n"
"background-color: rgb(104, 148, 0);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.send_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_btn.sizePolicy().hasHeightForWidth())
        self.send_btn.setSizePolicy(sizePolicy)
        self.send_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout.addWidget(self.send_btn)
        self.reset_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_btn.sizePolicy().hasHeightForWidth())
        self.reset_btn.setSizePolicy(sizePolicy)
        self.reset_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout.addWidget(self.reset_btn)
        self.back_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn.sizePolicy().hasHeightForWidth())
        self.back_btn.setSizePolicy(sizePolicy)
        self.back_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(ask_to_enter_win)
        self.send_btn.clicked.connect(ask_to_enter_win.send_ask)
        self.reset_btn.clicked.connect(ask_to_enter_win.reset)
        self.back_btn.clicked.connect(ask_to_enter_win.go_back)
        QtCore.QMetaObject.connectSlotsByName(ask_to_enter_win)

    def retranslateUi(self, ask_to_enter_win):
        _translate = QtCore.QCoreApplication.translate
        ask_to_enter_win.setWindowTitle(_translate("ask_to_enter_win", "Form"))
        self.led_signal.setText(_translate("ask_to_enter_win", "请输入请求"))
        self.house_num_text.setText(_translate("ask_to_enter_win", "单元号"))
        self.house_num_input.setItemText(0, _translate("ask_to_enter_win", "A1"))
        self.house_num_input.setItemText(1, _translate("ask_to_enter_win", "A2"))
        self.house_num_input.setItemText(2, _translate("ask_to_enter_win", "B1"))
        self.house_num_input.setItemText(3, _translate("ask_to_enter_win", "B2"))
        self.house_num_input.setItemText(4, _translate("ask_to_enter_win", "C1"))
        self.house_num_input.setItemText(5, _translate("ask_to_enter_win", "C2"))
        self.house_num_input.setItemText(6, _translate("ask_to_enter_win", "D1"))
        self.house_num_input.setItemText(7, _translate("ask_to_enter_win", "D2"))
        self.room_num_text.setText(_translate("ask_to_enter_win", "房号"))
        self.send_btn.setText(_translate("ask_to_enter_win", "发送请求"))
        self.reset_btn.setText(_translate("ask_to_enter_win", "重置"))
        self.back_btn.setText(_translate("ask_to_enter_win", "返回"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ask_to_enter_win = QtWidgets.QWidget()
    ui = Ui_ask_to_enter_win()
    ui.setupUi(ask_to_enter_win)
    ask_to_enter_win.show()
    sys.exit(app.exec_())
