# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_detector.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FPD(object):
    def setupUi(self, FPD):
        FPD.setObjectName("FPD")
        FPD.resize(552, 481)
        FPD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(FPD)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(FPD)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.enter_pw_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.enter_pw_btn.sizePolicy().hasHeightForWidth())
        self.enter_pw_btn.setSizePolicy(sizePolicy)
        self.enter_pw_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.enter_pw_btn.setMaximumSize(QtCore.QSize(200, 50))
        self.enter_pw_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color: rgb(0, 0, 0);")
        self.enter_pw_btn.setObjectName("enter_pw_btn")
        self.horizontalLayout_2.addWidget(self.enter_pw_btn)
        self.enter_request_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.enter_request_btn.sizePolicy().hasHeightForWidth())
        self.enter_request_btn.setSizePolicy(sizePolicy)
        self.enter_request_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.enter_request_btn.setMaximumSize(QtCore.QSize(200, 50))
        self.enter_request_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color: rgb(0, 0, 0);")
        self.enter_request_btn.setObjectName("enter_request_btn")
        self.horizontalLayout_2.addWidget(self.enter_request_btn)
        self.open_carmera_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.open_carmera_btn.sizePolicy().hasHeightForWidth())
        self.open_carmera_btn.setSizePolicy(sizePolicy)
        self.open_carmera_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.open_carmera_btn.setMaximumSize(QtCore.QSize(200, 50))
        self.open_carmera_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color: rgb(0, 0, 0);")
        self.open_carmera_btn.setObjectName("open_carmera_btn")
        self.horizontalLayout_2.addWidget(self.open_carmera_btn)
        self.close_carmera_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.close_carmera_btn.sizePolicy().hasHeightForWidth())
        self.close_carmera_btn.setSizePolicy(sizePolicy)
        self.close_carmera_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.close_carmera_btn.setMaximumSize(QtCore.QSize(200, 50))
        self.close_carmera_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color: rgb(0, 0, 0);")
        self.close_carmera_btn.setObjectName("close_carmera_btn")
        self.horizontalLayout_2.addWidget(self.close_carmera_btn)
        self.verticalLayout.addWidget(self.frame)
        self.carmera_shower = QtWidgets.QLabel(FPD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.carmera_shower.sizePolicy().hasHeightForWidth())
        self.carmera_shower.setSizePolicy(sizePolicy)
        self.carmera_shower.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 14pt \"Agency FB\";\n"
"color: rgb(255, 255, 255);\n"
"border:1px,solid,rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.carmera_shower.setAlignment(QtCore.Qt.AlignCenter)
        self.carmera_shower.setObjectName("carmera_shower")
        self.verticalLayout.addWidget(self.carmera_shower)
        self.suc_or_not_label = QtWidgets.QLabel(FPD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.suc_or_not_label.sizePolicy().hasHeightForWidth())
        self.suc_or_not_label.setSizePolicy(sizePolicy)
        self.suc_or_not_label.setMinimumSize(QtCore.QSize(0, 50))
        self.suc_or_not_label.setStyleSheet("#suc_or_not_label{\n"
"    background-color: rgb(159, 159, 159);\n"
"    font: 14pt \"Agency FB\";\n"
"}\n"
"\n"
"\n"
"")
        self.suc_or_not_label.setAlignment(QtCore.Qt.AlignCenter)
        self.suc_or_not_label.setObjectName("suc_or_not_label")
        self.verticalLayout.addWidget(self.suc_or_not_label)
        self.widget = QtWidgets.QWidget(FPD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_text = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_text.sizePolicy().hasHeightForWidth())
        self.name_text.setSizePolicy(sizePolicy)
        self.name_text.setMinimumSize(QtCore.QSize(150, 50))
        self.name_text.setMaximumSize(QtCore.QSize(150, 16777215))
        self.name_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Agency FB\";\n"
"border:1px,solid,rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.name_text.setAlignment(QtCore.Qt.AlignCenter)
        self.name_text.setObjectName("name_text")
        self.horizontalLayout.addWidget(self.name_text)
        self.house_text = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.house_text.sizePolicy().hasHeightForWidth())
        self.house_text.setSizePolicy(sizePolicy)
        self.house_text.setMinimumSize(QtCore.QSize(150, 50))
        self.house_text.setMaximumSize(QtCore.QSize(150, 16777215))
        self.house_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Agency FB\";\n"
"border:1px,solid,rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.house_text.setAlignment(QtCore.Qt.AlignCenter)
        self.house_text.setObjectName("house_text")
        self.horizontalLayout.addWidget(self.house_text)
        self.room_text = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.room_text.sizePolicy().hasHeightForWidth())
        self.room_text.setSizePolicy(sizePolicy)
        self.room_text.setMinimumSize(QtCore.QSize(150, 50))
        self.room_text.setMaximumSize(QtCore.QSize(150, 16777215))
        self.room_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Agency FB\";\n"
"border:1px,solid,rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.room_text.setAlignment(QtCore.Qt.AlignCenter)
        self.room_text.setObjectName("room_text")
        self.horizontalLayout.addWidget(self.room_text)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(FPD)
        self.open_carmera_btn.clicked.connect(FPD.open_carmera)
        self.close_carmera_btn.clicked.connect(FPD.close_camera)
        self.enter_pw_btn.clicked.connect(FPD.open_pw_input)
        self.enter_request_btn.clicked.connect(FPD.open_ask_to_enter)
        QtCore.QMetaObject.connectSlotsByName(FPD)

    def retranslateUi(self, FPD):
        _translate = QtCore.QCoreApplication.translate
        FPD.setWindowTitle(_translate("FPD", "FPD人脸识别门禁系统"))
        self.enter_pw_btn.setText(_translate("FPD", "输入密码"))
        self.enter_request_btn.setText(_translate("FPD", "发送进入请求"))
        self.open_carmera_btn.setText(_translate("FPD", "开启摄像头"))
        self.close_carmera_btn.setText(_translate("FPD", "关闭摄像头"))
        self.carmera_shower.setText(_translate("FPD", "请打开摄像头"))
        self.suc_or_not_label.setText(_translate("FPD", "未识别到人脸"))
        self.name_text.setText(_translate("FPD", "姓名"))
        self.house_text.setText(_translate("FPD", "单元号"))
        self.room_text.setText(_translate("FPD", "房号"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FPD = QtWidgets.QWidget()
    ui = Ui_FPD()
    ui.setupUi(FPD)
    FPD.show()
    sys.exit(app.exec_())
