# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pw_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pw_input_win(object):
    def setupUi(self, pw_input_win):
        pw_input_win.setObjectName("pw_input_win")
        pw_input_win.resize(400, 300)
        self.layoutWidget = QtWidgets.QWidget(pw_input_win)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 361, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pw_label = QtWidgets.QLabel(self.layoutWidget)
        self.pw_label.setObjectName("pw_label")
        self.gridLayout.addWidget(self.pw_label, 0, 0, 1, 1)
        self.pw_text = QtWidgets.QLineEdit(self.layoutWidget)
        self.pw_text.setObjectName("pw_text")
        self.gridLayout.addWidget(self.pw_text, 0, 1, 1, 2)
        self.btn_1 = my_special_btn(self.layoutWidget)
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 1, 0, 1, 1)
        self.btn_2 = my_special_btn(self.layoutWidget)
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 1, 1, 1, 1)
        self.btn_3 = my_special_btn(self.layoutWidget)
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 1, 2, 1, 1)
        self.btn_4 = my_special_btn(self.layoutWidget)
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 2, 0, 1, 1)
        self.btn_5 = my_special_btn(self.layoutWidget)
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 2, 1, 1, 1)
        self.btn_6 = my_special_btn(self.layoutWidget)
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 2, 2, 1, 1)
        self.btn_7 = my_special_btn(self.layoutWidget)
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 3, 0, 1, 1)
        self.btn_8 = my_special_btn(self.layoutWidget)
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 3, 1, 1, 1)
        self.btn_9 = my_special_btn(self.layoutWidget)
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 3, 2, 1, 1)
        self.btn_0 = my_special_btn(self.layoutWidget)
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 4, 0, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 4, 1, 1, 1)
        self.btn_ok = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_ok.setObjectName("btn_ok")
        self.gridLayout.addWidget(self.btn_ok, 4, 2, 1, 1)

        self.retranslateUi(pw_input_win)
        self.btn_1.btn_pressed.connect(pw_input_win.show_num)
        self.btn_2.btn_pressed.connect(pw_input_win.show_num)
        self.btn_3.btn_pressed.connect(pw_input_win.show_num)
        self.btn_4.btn_pressed.connect(pw_input_win.show_num)
        self.btn_5.btn_pressed.connect(pw_input_win.show_num)
        self.btn_6.btn_pressed.connect(pw_input_win.show_num)
        self.btn_7.btn_pressed.connect(pw_input_win.show_num)
        self.btn_8.btn_pressed.connect(pw_input_win.show_num)
        self.btn_9.btn_pressed.connect(pw_input_win.show_num)
        self.btn_0.btn_pressed.connect(pw_input_win.show_num)
        self.btn_clear.clicked.connect(pw_input_win.clearall)
        self.btn_ok.clicked.connect(pw_input_win.create_threading)
        QtCore.QMetaObject.connectSlotsByName(pw_input_win)

    def retranslateUi(self, pw_input_win):
        _translate = QtCore.QCoreApplication.translate
        pw_input_win.setWindowTitle(_translate("pw_input_win", "Form"))
        self.pw_label.setText(_translate("pw_input_win", "请输入密码"))
        self.btn_1.setText(_translate("pw_input_win", "1"))
        self.btn_2.setText(_translate("pw_input_win", "2"))
        self.btn_3.setText(_translate("pw_input_win", "3"))
        self.btn_4.setText(_translate("pw_input_win", "4"))
        self.btn_5.setText(_translate("pw_input_win", "5"))
        self.btn_6.setText(_translate("pw_input_win", "6"))
        self.btn_7.setText(_translate("pw_input_win", "7"))
        self.btn_8.setText(_translate("pw_input_win", "8"))
        self.btn_9.setText(_translate("pw_input_win", "9"))
        self.btn_0.setText(_translate("pw_input_win", "0"))
        self.btn_clear.setText(_translate("pw_input_win", "清空"))
        self.btn_ok.setText(_translate("pw_input_win", "确认"))
from special_btn import my_special_btn


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pw_input_win = QtWidgets.QWidget()
    ui = Ui_pw_input_win()
    ui.setupUi(pw_input_win)
    pw_input_win.show()
    sys.exit(app.exec_())
